name: Notify Discord on PR Merge

on:
  pull_request:
    types: [closed]  # Only fires when PR is closed

jobs:
  notify-discord:
    if: github.event.pull_request.merged == true  # Only run if it was merged
    runs-on: ubuntu-latest
    steps:
      - name: Send PR merge notification to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "content": "✅ **Pull Request Merged!**\n**Title**: ${{ github.event.pull_request.title }}\n**By**: ${{ github.event.pull_request.user.login }}\n**Link**: ${{ github.event.pull_request.html_url }}"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
